// <auto-generated />
using System;
using ATI.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ATI.Migrations
{
    [DbContext(typeof(ATIDbContext))]
    [Migration("20260306150000_AddProcedureTypesIncrementally")]
    partial class AddProcedureTypesIncrementally
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a SQL-based migration, model builder not used
        }
    }
}
