<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ATI.Revenue.Web</RootNamespace>
    <AssemblyName>ATI.Revenue.Web</AssemblyName>
    <IsPublishable>false</IsPublishable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Abp.AspNetZeroCore.Web" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ATI.Web.Core\ATI.Web.Core.csproj" />
    <ProjectReference Include="..\Revenue.Application\ATI.Revenue.Application.csproj" />
    <ProjectReference Include="..\Revenue.EntityFrameworkCore\ATI.Revenue.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Revenue\Data\" />
    <Folder Include="Areas\Revenue\ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
    <Content Update="appsettings.Development.json">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <Target Name="CopyRevenueScriptsToWebMvc" AfterTargets="Build">
    <ItemGroup>
      <ScriptFiles Include="wwwroot\view-resources\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(ScriptFiles)"
          DestinationFiles="@(ScriptFiles->'..\..\src\ATI.Web.Mvc\wwwroot\view-resources\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
  </Target>

  <Target Name="CopyRevenueViewsToWebMvc" AfterTargets="Build">
    <ItemGroup>
      <ViewFiles Include="Areas\Revenue\Views\**\*.cshtml" />
    </ItemGroup>
    <Copy SourceFiles="@(ViewFiles)"
          DestinationFiles="@(ViewFiles->'..\..\src\ATI.Web.Mvc\Areas\Revenue\Views\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
