//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Pharmacy.Domain.Entities
{
    using Abp.Authorization.Users;
    using Abp.Domain.Entities;
    using ATI.Admin.Domain.Entities;
    using ATI.Authorization.Users;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.EntityFrameworkCore.Metadata.Internal;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Doctor : Entity<int>
    {
        public Doctor()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }

        public Nullable<long> UserId { get; set; }
        public string Specialty { get; set; }
        public string LicenseNumber { get; set; }
        public string SignatureFileID { get; set; }

        public virtual ICollection<Prescription> Prescriptions { get; set; }
        public int? TenantId { get; set; }

        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
        //public virtual ICollection<UserCompany> UserCompanies { get; set; }

    }
}
