//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Pharmacy.Domain.Entities
{
    using Abp.Domain.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance : Entity<int>, IMayHaveTenant
    {
        public int? TenantId { get; set; }
        public Insurance()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public string InsuranceProvider { get; set; }
        public string PolicyNumber { get; set; }
        public string? CoverageDetails { get; set; }
    
        public string Bin { get; set; }

        public string PCN { get; set; }

        public string Group { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
