//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Pharmacy.Domain.Entities
{
    using Abp.Domain.Entities;
    using System;
    using System.Collections.Generic;

    public partial class Inventory : Entity<int>
    {
 
        public Nullable<int> MedicationId { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
    
        public virtual Medication Medication { get; set; }
    }
}
