//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Pharmacy.Domain.Entities
{
    using Abp.Domain.Entities;
    using ATI.Admin.Domain.Entities;
    using ATI.Authorization.Users;
    using System;
    using System.Collections.Generic;

    public partial class Patient : Entity<int>
    {

        public Patient()
        {
            this.PatientAllergies = new HashSet<PatientAllergy>();
            this.Prescriptions = new HashSet<Prescription>();
            this.Address = new Address();
            this.Insurance = new Insurance();
        }

        public Nullable<long> UserId { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactPhone { get; set; }

        public virtual Insurance Insurance { get; set; }
        public virtual ICollection<PatientAllergy> PatientAllergies { get; set; }

        public virtual ICollection<Prescription> Prescriptions { get; set; }
        // public virtual Personnel Personnel { get; set; }
        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
        public int? TenantId { get; set; }
        public int? DoctorId { get; set; }
        public Doctor? Doctor { get; set; }
        public void AddAllergy(PatientAllergy item) { item.Patient = this; PatientAllergies.Add(item); }
        public void RemoveAllergy(PatientAllergy item) { item.Patient = this; PatientAllergies.Remove(item); }

    }
}
