//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Pharmacy.Domain.Entities
{
    using Abp.Domain.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionHistory : Entity<int>, IMayHaveTenant
    {
        public int? TenantId { get; set; }

        public Nullable<int> PrescriptionId { get; set; }
        public Nullable<int> PreviousPrescriptionId { get; set; }
        public string RefillHistory { get; set; }
        public string PreviousMedications { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
