//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Pharmacy.Domain.Entities
{
    using Abp.Domain.Entities;
    using System;
    using System.Collections.Generic;

    public partial class PrescriptionItem : Entity<int>, IMayHaveTenant
    {
        public int? TenantId { get; set; }
        public Nullable<int> PrescriptionId { get; set; }
        public Nullable<int> MedicationId { get; set; }
        public string Dosage { get; set; }
        public string Frequency { get; set; }
        public string RouteOfAdministration { get; set; }
        public string Duration { get; set; }
        public string SpecialInstructions { get; set; }
        public string RefillInformation { get; set; }
        public Nullable<int> RefillsAllowed { get; set; }
        public Nullable<int> RefillsRemaining { get; set; }
        public Nullable<DateTime> StartDateTime { get; set; }
        public Nullable<DateTime> EndDateTime { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public string Instructions { get; set; }
        public virtual Medication Medication { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
