//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Pharmacy.Domain.Entities
{
    using Abp.Domain.Entities;
    using Abp.Domain.Entities.Auditing;
    using ATI.Admin.Domain.Entities;
    using Castle.Windsor.Diagnostics.Extensions;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using System;
    using System.Collections.Generic;


    public partial class Prescription : AuditedAggregateRoot<int>
    {
        public Prescription()
        {
            this.PrescriptionItems = new HashSet<PrescriptionItem>();
            this.PrescriptionHistories = new HashSet<PrescriptionHistory>();
            this.Transactions = new HashSet<Transaction>();
        }

        public Nullable<int> PrescriptionStatusId { get; set; }
        public Nullable<System.DateTime> PrescriptionDate { get; set; }
        public string Notes { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public string PatientName { get; set; }
        public string PatientAddress { get; set; }
        public string PatientPhone { get; set; }
        public Nullable<System.DateTime> PatientDateOfBirth { get; set; }
        public virtual Facility PrescriberFacility { get; set; }
        public virtual Nullable<int> PrescriberFacilityId { get; set; }
        public string? PrescriberName { get; set; }
        public string? PrescriberOfficePhone { get; set; }
        public string? PrescriberOfficeFax { get; set; }
        public virtual Nullable<int> PatientId { get; set; }
        public virtual Nullable<int> DoctorId { get; set; }
        public virtual Nullable<int> DosageRouteId { get; set; }
        public virtual string BinaryFileId { get; set; }

        public Nullable<int> DeliveryTypeId { get; set; }
        public Nullable<int> BillingTo { get; set; }

        public string? PersonFaxing { get; set; }

        public string? DrugAllergies { get; set; }

        public string? PrescriberAddress1 { get; set; }
        public string? PrescriberAddress2 { get; set; }
        public string? PrescriberNPI { get; set; }
        public string PrescriberSignatureFileID { get; set; }

        public Facility Pharmacy { get; set; }
        public string? ClinicName { get; set; }
        public string? PharmacyAddress { get; set; }

        public string? DeliveryAddress { get; set; }


        public virtual ICollection<PrescriptionItem> PrescriptionItems { get; set; }

        public virtual ICollection<PrescriptionHistory> PrescriptionHistories { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }

        public void AddPrescriptionItem(PrescriptionItem item) { PrescriptionItems.Add(item); }

        public void ClearPrescriptionItems() { PrescriptionItems.Clear(); }

        public void RemovePrescrriptionItem(PrescriptionItem item) { PrescriptionItems.Remove(item); }

    }
}
