//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Admin.Domain.Entities
{
    using Abp.Domain.Entities.Auditing;
    using System;
    using System.Collections.Generic;
    
    public partial class Company:FullAuditedEntity
    {
          public Company()
        {
            this.UserCompanies = new HashSet<UserCompany>();
        }
           
        public Nullable<int> CompanyTypeId { get; set; }
        public Nullable<int> CompanyStatusId { get; set; }
        public string CompanyName { get; set; }
      
        public virtual Address Address { get; set; }

        public int BillTo { get; set; }

        public int DeliveryTypeId { get; set; }

        public virtual ICollection<UserCompany> UserCompanies { get; set; }
    }
}
