//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Admin.Domain.Entities
{
    using Abp.Domain.Entities.Auditing;
    using System;
    using System.Collections.Generic;

    public partial class Facility : FullAuditedEntity
    {

        public Facility()
        {
            //this.Prescriptions = new HashSet<Prescription>();
        }

        public string FacilityName { get; set; }
        public virtual Address Address { get; set; }
        public Nullable<int> AddressId { get; set; }

        public Nullable<int> FacilityStatusId { get; set; }

        public virtual Company Company { get; set; }


    }
}
