//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Admin.Domain.Entities
{
    using Abp.Authorization.Users;
    using Abp.Domain.Entities;
    using ATI.Authorization.Users;
    using System;
    using System.Collections.Generic;

    public partial class UserCompany : Entity<int>
    {
        public int CompanyId { get; set; }
        public int FacilityId { get; set; }
        public virtual Company Company { get; set; }
        public virtual Facility Facility { get; set; }
        public long? UserId { get; set; }

        public int? UserTypeId { get; set; }
        public bool IsDefaultFacility { get; set; }


    }
}
